### ISSUE TITLE
Form class name

### ISSUE THREAD

**Issue by sTefbured** [sTefbuyellow/vsrpp_labs#1]
https://github.com/sTefbuyellow/vsrpp_labs/blob/55f54d05436bf53896df05a02d896e8a86314380/lab_01/bntu.vsrpp.kkirichuk/bntu.vsrpp.kkirichuk.lab2/Form1.cs#L12

Kirya, you have a form called `Form1` in your project. As Dovnar said, he hates when a class has a default name which does not describe its purpose.
You could call it "ApplicationForm", "MainForm" etc.
Good luck, cow♂BOY♂

**Comment by sTefbuyellow** [comment]
I closed WSRPP with A+, so I dont give a fuck

Best regrets
---------------------------------
Kiryl Kirychuk, Junior Software Ingener 
please don't call me

**Comment by sTefbured** [comment]
> I closed WSRPP with A+, so I dont give a fuck

Please, mind your language.
